owner: YOUR_GITHUB_USERNAME     # Replace with your GitHub username
git-repo: YOUR_REPO_NAME       # Replace with your repository name
charts-dir: charts
target-branch: main
pages-branch: gh-pages
package-path: .cr-release-packages
index-path: index.yaml
skip-existing: true
generate-release-notes: true
make-release-latest: true
