{{/*
Copyright (c) 2024, Itential, Inc
GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
*/}}
{{- range $i := until (.Values.replicaCount | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.service.name }}-headless-{{ $i }}
  labels:
    {{- include "iap.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "service"
  annotations:
    helm.sh/template-file: "{{ $.Template.Name }}"
    kubernetes.io/description: "Itential Automation Platform headless service to individual pods"
spec:
  selector:
    {{- include "iap.selectorLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ include "iap.fullname" $ }}-{{ $i }}
  ports:
  - name: https
    port: {{ $.Values.service.port }}
    targetPort: {{ $.Values.applicationPort }}
{{- end }}