{{- if and .Values.ingress.enabled .Values.processExporter.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "iap.fullname" . }}-metrics-ingress
  labels:
    {{- include "iap.labels" . | nindent 4 }}
    app.kubernetes.io/component: "metrics-ingress"
  annotations:
    kubernetes.io/description: "Itential Automation Platform Metrics Ingress. HTTP-only for process-exporter."
    {{- include "iap.annotations" . | nindent 4 }}
    # Metrics-specific annotations - use HTTP backend protocol
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    alb.ingress.kubernetes.io/healthcheck-path: "/metrics"
    alb.ingress.kubernetes.io/healthcheck-port: "9256"
    alb.ingress.kubernetes.io/healthcheck-protocol: "HTTP"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 9256}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=60
    alb.ingress.kubernetes.io/load-balancer-name: "itential-iap-metrics-lb-{{ .Release.Namespace }}"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
    external-dns.alpha.kubernetes.io/hostname: iap-metrics-{{ .Release.Namespace }}.{{ .Values.certificate.domain }}
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- range $i := until (.Values.replicaCount | int) }}
  - host: {{ printf "iap-metrics-%s-%d.%s" $.Release.Namespace $i $.Values.certificate.domain | quote }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "iap.fullname" $ }}-service-headless-{{ $i }}
            port:
              number: 9256
        path: "/"
        pathType: {{ $.Values.ingress.pathType | default "Prefix" }}
  {{- end }}
{{- end }}